server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: taojian
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.jiantao.mall.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml